dist: trusty
sudo: required
language: go
go:
- "1.11"
install:
- go get -u golang.org/x/lint/golint
script:
- golint skytap
- make build
- make test
- make vet
branches:
  only:
  - v2
  - master  
matrix:
  fast_finish: true
  allow_failures:
  - go: tip

